# Generated by Django 4.2.3 on 2023-07-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartProduct',
            new_name='CartItem',
        ),
        migrations.RenameModel(
            old_name='Visit',
            new_name='View',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='details',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='slider/'),
        ),
    ]
