# Generated by Django 4.2.3 on 2023-07-27 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_parent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='View',
            new_name='Visit',
        ),
    ]
